services:
  - type: web
    name: ai-hiring-portal
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn python_portal:app
    autoDeploy: true
